import { useEffect, useMemo, useRef, useState } from "react";
import { downloadText, exportCsv, exportMidi } from "./export";
import MelodyPanel, { midiName, type MelodyNote } from "./MelodyPanel";
import { transposeChord, transposeKey } from "./music";

type ChordCandidate = { chord: string; confidence: number };
type ChordSegment = { start: number; end: number; chord: string; confidence: number; candidates: ChordCandidate[]; bar: number; beat: number };
type AnalysisResult = { duration: number; sampleRate: number; tempo: number; key: string; beatDuration: number; beatOffset: number; beatsPerBar: number; beatUnit: number; timeSignature: string; meterConfidence: number; chords: ChordSegment[]; melody: MelodyNote[] };
type AnalysisProject = { format: "mfs-analysis"; version: 1; sourceName: string; savedAt: string; result: AnalysisResult };
type WorkerResponse = { type: "result"; result: AnalysisResult } | { type: "error"; message: string };

const AUTOSAVE_KEY = "mfs.autosave.v1";
function formatTime(seconds: number): string { const minutes = Math.floor(seconds / 60); const rest = Math.floor(seconds % 60).toString().padStart(2, "0"); return `${minutes}:${rest}`; }
function safeName(name: string): string { return name.replace(/\.[^.]+$/, "").replace(/[^\p{L}\p{N}_-]+/gu, "_") || "analysis"; }
function buildPeaks(samples: Float32Array, count = 1000): number[] { if (!samples.length) return []; const size = Math.max(1, Math.ceil(samples.length / count)); const peaks: number[] = []; for (let start = 0; start < samples.length; start += size) { let peak = 0; const end = Math.min(start + size, samples.length); for (let index = start; index < end; index += 1) peak = Math.max(peak, Math.abs(samples[index])); peaks.push(peak); } const maximum = Math.max(...peaks, 1e-6); return peaks.map((value) => value / maximum); }
function normalizeNoChord(result: AnalysisResult, peaks: number[]): AnalysisResult { if (!peaks.length || result.duration <= 0) return result; return { ...result, melody: result.melody ?? [], chords: result.chords.map((item) => { const from = Math.max(0, Math.floor(item.start / result.duration * peaks.length)); const to = Math.min(peaks.length, Math.ceil(item.end / result.duration * peaks.length)); const section = peaks.slice(from, Math.max(from + 1, to)); const level = section.reduce((sum, value) => sum + value, 0) / Math.max(1, section.length); if ((level >= 0.02 && item.confidence >= 0.44) || item.chord === "N") return item; return { ...item, chord: "N", confidence: Math.max(item.confidence, 0.58), candidates: [{ chord: "N", confidence: 0.8 }, ...item.candidates.filter((candidate) => candidate.chord !== "N")].slice(0, 3) }; }) }; }

function Waveform({ peaks, duration, currentTime, onSeek }: { peaks: number[]; duration: number; currentTime: number; onSeek: (seconds: number) => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas || !peaks.length) return; const ratio = window.devicePixelRatio || 1; const width = canvas.clientWidth; const height = canvas.clientHeight; canvas.width = Math.max(1, Math.floor(width * ratio)); canvas.height = Math.max(1, Math.floor(height * ratio)); const context = canvas.getContext("2d"); if (!context) return; context.setTransform(ratio, 0, 0, ratio, 0, 0); context.clearRect(0, 0, width, height); const center = height / 2; const progress = duration > 0 ? Math.min(1, currentTime / duration) : 0; const barWidth = width / peaks.length; for (let index = 0; index < peaks.length; index += 1) { const amplitude = Math.max(1, peaks[index] * height * 0.43); context.fillStyle = index / peaks.length <= progress ? "#8ca9ff" : "#34415f"; context.fillRect(index * barWidth, center - amplitude, Math.max(1, barWidth), amplitude * 2); } context.fillStyle = "#fff"; context.fillRect(Math.min(width - 1, Math.max(0, progress * width)), 0, 1, height); }, [currentTime, duration, peaks]);
  return <canvas ref={canvasRef} className="waveform" aria-label="波形" onClick={(event) => { const bounds = event.currentTarget.getBoundingClientRect(); onSeek((event.clientX - bounds.left) / bounds.width * duration); }} />;
}

export default function App() {
  const [file, setFile] = useState<File | null>(null); const [sourceName, setSourceName] = useState("Unknown"); const [audioUrl, setAudioUrl] = useState(""); const [status, setStatus] = useState("音源を選択してください"); const [result, setResult] = useState<AnalysisResult | null>(null); const [busy, setBusy] = useState(false); const [currentTime, setCurrentTime] = useState(0); const [peaks, setPeaks] = useState<number[]>([]); const [history, setHistory] = useState<AnalysisResult[]>([]); const [future, setFuture] = useState<AnalysisResult[]>([]);
  const inputRef = useRef<HTMLInputElement>(null); const projectInputRef = useRef<HTMLInputElement>(null); const audioRef = useRef<HTMLAudioElement>(null);
  useEffect(() => () => { if (audioUrl) URL.revokeObjectURL(audioUrl); }, [audioUrl]);
  useEffect(() => { try { const saved = localStorage.getItem(AUTOSAVE_KEY); if (!saved) return; const project = JSON.parse(saved) as AnalysisProject; if (project.format === "mfs-analysis" && project.result?.chords) { setResult({ ...project.result, melody: project.result.melody ?? [] }); setSourceName(project.sourceName || "Autosave"); setStatus("前回の編集内容を自動復元しました"); } } catch { localStorage.removeItem(AUTOSAVE_KEY); } }, []);
  useEffect(() => { if (!result) return; const project: AnalysisProject = { format: "mfs-analysis", version: 1, sourceName, savedAt: new Date().toISOString(), result }; localStorage.setItem(AUTOSAVE_KEY, JSON.stringify(project)); }, [result, sourceName]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement) return; if (event.code === "Space" && audioRef.current) { event.preventDefault(); void (audioRef.current.paused ? audioRef.current.play() : audioRef.current.pause()); } if (event.code === "ArrowLeft") seekTo(currentTime - 5); if (event.code === "ArrowRight") seekTo(currentTime + 5); if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "z") { event.preventDefault(); event.shiftKey ? redo() : undo(); } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); });
  const activeChordIndex = useMemo(() => result?.chords.findIndex((item) => currentTime >= item.start && currentTime < item.end) ?? -1, [currentTime, result]);
  const chordPro = useMemo(() => { if (!result) return ""; const bars = new Map<number, string[]>(); for (const item of result.chords) { const values = bars.get(item.bar) ?? []; if (values.at(-1) !== item.chord) values.push(item.chord); bars.set(item.bar, values); } const body = [...bars.values()].map((items) => `| ${items.join(" ")} `).join("") + "|"; return `{title: ${sourceName}}\n{key: ${result.key}}\n{tempo: ${Math.round(result.tempo)}}\n{time: ${result.timeSignature}}\n\n${body}`; }, [result, sourceName]);
  function commit(next: AnalysisResult): void { if (result) setHistory((items) => [...items.slice(-49), result]); setFuture([]); setResult(next); }
  function undo(): void { const previous = history.at(-1); if (!previous || !result) return; setHistory((items) => items.slice(0, -1)); setFuture((items) => [result, ...items].slice(0, 50)); setResult(previous); }
  function redo(): void { const next = future[0]; if (!next || !result) return; setFuture((items) => items.slice(1)); setHistory((items) => [...items, result].slice(-50)); setResult(next); }
  function selectFile(next: File | null): void { if (audioUrl) URL.revokeObjectURL(audioUrl); setFile(next); setSourceName(next?.name ?? "Unknown"); setAudioUrl(next ? URL.createObjectURL(next) : ""); setResult(null); setPeaks([]); setHistory([]); setFuture([]); setCurrentTime(0); setStatus(next ? `${next.name} を選択しました` : "音源を選択してください"); }
  async function analyze(): Promise<void> { if (!file || busy) return; setBusy(true); setResult(null); setHistory([]); setFuture([]); setStatus("音声をデコード中…"); try { const context = new AudioContext(); const decoded = await context.decodeAudioData(await file.arrayBuffer()); const mono = new Float32Array(decoded.length); for (let channel = 0; channel < decoded.numberOfChannels; channel += 1) { const data = decoded.getChannelData(channel); for (let index = 0; index < mono.length; index += 1) mono[index] += data[index] / decoded.numberOfChannels; } await context.close(); const nextPeaks = buildPeaks(mono); setPeaks(nextPeaks); setStatus("WASMでコードと主旋律を同時解析中…"); const worker = new Worker(new URL("./audio/analysis-worker.ts", import.meta.url), { type: "module" }); worker.onmessage = (event: MessageEvent<WorkerResponse>) => { if (event.data.type === "result") { setResult(normalizeNoChord(event.data.result, nextPeaks)); setStatus("解析完了。コード譜とメロディを編集・MIDI出力できます"); } else setStatus(`解析失敗: ${event.data.message}`); setBusy(false); worker.terminate(); }; worker.onerror = (event) => { setStatus(`Workerエラー: ${event.message}`); setBusy(false); worker.terminate(); }; worker.postMessage({ samples: mono, sampleRate: decoded.sampleRate }, [mono.buffer]); } catch (error) { setStatus(error instanceof Error ? error.message : "解析に失敗しました"); setBusy(false); } }
  function seekTo(seconds: number): void { const value = Math.max(0, Math.min(seconds, result?.duration ?? seconds)); if (audioRef.current) audioRef.current.currentTime = value; setCurrentTime(value); }
  function editChord(index: number, chord: string): void { if (!result) return; commit({ ...result, chords: result.chords.map((item, itemIndex) => itemIndex === index ? { ...item, chord } : item) }); }
  function editMelody(melody: MelodyNote[]): void { if (!result) return; commit({ ...result, melody }); }
  function transpose(semitones: number): void { if (!result) return; commit({ ...result, key: transposeKey(result.key, semitones), chords: result.chords.map((item) => ({ ...item, chord: transposeChord(item.chord, semitones), candidates: item.candidates.map((candidate) => ({ ...candidate, chord: transposeChord(candidate.chord, semitones) })) })), melody: result.melody.map((note) => { const midi = Math.max(0, Math.min(127, note.midi + semitones)); return { ...note, midi, note: midiName(midi), frequency: 440 * 2 ** ((midi - 69) / 12) }; }) }); setStatus(`${semitones > 0 ? "+" : ""}${semitones}半音移調しました`); }
  async function copyChordPro(): Promise<void> { await navigator.clipboard.writeText(chordPro); setStatus("ChordProをコピーしました"); }
  function downloadProject(): void { if (!result) return; const project: AnalysisProject = { format: "mfs-analysis", version: 1, sourceName, savedAt: new Date().toISOString(), result }; downloadText(`${safeName(sourceName)}.mfs.json`, JSON.stringify(project, null, 2), "application/json"); }
  async function loadProject(next: File | null): Promise<void> { if (!next) return; try { const project = JSON.parse(await next.text()) as AnalysisProject; if (project.format !== "mfs-analysis" || project.version !== 1 || !project.result?.chords) throw new Error("MFS解析JSONではありません"); setResult({ ...project.result, melody: project.result.melody ?? [] }); setSourceName(project.sourceName || next.name); setCurrentTime(0); setHistory([]); setFuture([]); setStatus("解析JSONを読み込みました"); } catch (error) { setStatus(error instanceof Error ? error.message : "JSONを読み込めませんでした"); } }

  return <main className="shell">
    <section className="hero"><p className="eyebrow">MFS / MUSIC FROM SOUND</p><h1>音源から、コード譜とメロディへ。</h1><p className="lead">音源は端末外へ送信しません。2つのRust/WASM解析器でコード進行と主旋律を同時に採譜します。</p></section>
    <section className="panel upload" onClick={() => inputRef.current?.click()}><input ref={inputRef} type="file" accept="audio/*,.mp3,.wav,.m4a,.ogg,.flac" hidden onChange={(event) => selectFile(event.target.files?.[0] ?? null)} /><strong>{file ? file.name : "音声ファイルを選択"}</strong><span>{file ? `${(file.size / 1024 / 1024).toFixed(1)} MB` : "MP3 / WAV / M4A / OGG / FLAC"}</span></section>
    {audioUrl && <audio className="player" ref={audioRef} src={audioUrl} controls onTimeUpdate={(event) => setCurrentTime(event.currentTarget.currentTime)} />}
    {peaks.length > 0 && result && <Waveform peaks={peaks} duration={result.duration} currentTime={currentTime} onSeek={seekTo} />}
    <div className="actions"><button disabled={!file || busy} onClick={() => void analyze()}>{busy ? "解析中…" : "コード＋メロディ解析"}</button><button className="secondary" onClick={() => projectInputRef.current?.click()}>プロジェクトを開く</button><input ref={projectInputRef} type="file" accept="application/json,.json" hidden onChange={(event) => void loadProject(event.target.files?.[0] ?? null)} /><span className="status">{status}</span></div>
    {result && <section className="results">
      <div className="metrics"><article><span>BPM</span><strong>{Math.round(result.tempo)}</strong></article><article><span>Key</span><strong>{result.key}</strong></article><article><span>拍子</span><strong>{result.timeSignature}</strong><small>{Math.round(result.meterConfidence * 100)}%</small></article><article><span>Melody</span><strong>{result.melody.length}</strong><small>notes</small></article></div>
      <div className="panel toolbar"><div><b>編集</b><button className="secondary" disabled={!history.length} onClick={undo}>元に戻す</button><button className="secondary" disabled={!future.length} onClick={redo}>やり直す</button></div><div><b>全体移調</b><button className="secondary" onClick={() => transpose(-1)}>−1</button><button className="secondary" onClick={() => transpose(1)}>＋1</button><button className="secondary" onClick={() => transpose(-12)}>−12</button><button className="secondary" onClick={() => transpose(12)}>＋12</button></div></div>
      <MelodyPanel notes={result.melody} duration={result.duration} currentTime={currentTime} onSeek={seekTo} onChange={editMelody} />
      <div className="panel"><div className="panelTitle"><h2>コード譜</h2><span>{result.chords.length} frames / Spaceで再生</span></div><div className="timeline">{result.chords.map((item, index) => <div className={`chord ${activeChordIndex === index ? "active" : ""} ${item.beat === 1 ? "barStart" : ""} ${item.chord === "N" ? "noChord" : ""}`} key={`${item.start}-${index}`} onClick={() => seekTo(item.start)}><div className="position"><b>{item.bar}</b><span>{item.beat}/{result.beatsPerBar}</span></div><input aria-label={`小節${item.bar} 拍${item.beat}`} value={item.chord} onClick={(event) => event.stopPropagation()} onChange={(event) => editChord(index, event.target.value)} /><div className="candidates" onClick={(event) => event.stopPropagation()}>{[...item.candidates, { chord: "N", confidence: 0.5 }].filter((candidate, candidateIndex, all) => all.findIndex((value) => value.chord === candidate.chord) === candidateIndex).slice(0, 4).map((candidate) => <button key={candidate.chord} className={candidate.chord === item.chord ? "selected" : ""} onClick={() => editChord(index, candidate.chord)}>{candidate.chord}</button>)}</div><span>{formatTime(item.start)}–{formatTime(item.end)}</span><small>{Math.round(item.confidence * 100)}%</small></div>)}</div></div>
      <div className="panel"><div className="panelTitle"><h2>書き出し</h2><span>MIDIはコード＋メロディの2トラック</span></div><div className="exportActions"><button className="secondary" onClick={() => void copyChordPro()}>ChordProをコピー</button><button className="secondary" onClick={() => downloadText(`${safeName(sourceName)}.cho`, chordPro)}>ChordPro保存</button><button className="secondary" onClick={downloadProject}>MFS JSON</button><button className="secondary" onClick={() => exportCsv(sourceName, result)}>CSV</button><button className="secondary" onClick={() => exportMidi(sourceName, result)}>MIDI</button></div><pre>{chordPro}</pre></div>
    </section>}
  </main>;
}
